# WireGuard env
### Server 
wireguard_server_interface_addr: "10.200.40.1/24"
wireguard_server_interface_port: 55555

### User
wireguard_user_interface_addr: "10.200.40.2/32"
wireguard_user_interface_dns: "1.1.1.1"
wireguard_allowedips: "0.0.0.0/0"

wireguard_local_conf_dir: "~/wireguard"
